### ISSUE TITLE
Error on clipdel with special characters

### ISSUE THREAD

**Issue by vxcamiloxv** [cdown/clipmenu#114] opened 2019-11-16 00:38 UTC
I called `clipdel -d 'e.g.passX\(sghs'`  for try to delete a password with special characters `(generated with pass)` I get the next error:
```sh
sed: -e expression #1, char 36: Unmatched ) or \)
sed: -e expression #1, char 36: Unmatched ) or \)
sed: -e expression #1, char 36: Unmatched ) or \)
```
I tried to escape the password but it not worked
```sh
    value=
    clipdel -d $(printf '%q' "$(xsel -b)")
```

**Comment by cdown** [comment] 2020-03-24 01:28
Yeah, this is a bug due to the fact we use `sed` without special escaping of the inputs. I'll look at fixing it for the next release.

**Comment by cdown** [comment] 2020-03-25 19:50
Oh wait, it's not a bug. By contract `-d` takes a BRE regex :-)

Try not escaping `(`.

**Comment by vxcamiloxv** [comment] 2020-03-25 21:11
@cdown 'e.g.passX\(sghs' is password without escaping, so I think one option is be able to call  without -d or with another option to delete a literal string without regex

**Comment by cdown** [comment] 2020-03-25 21:20
There's no need to escape anything. `(` in BRE means `(`.

**Comment by vxcamiloxv** [comment] 2020-03-25 21:29
@cdown `\` and `(` are part of the password

![screenshot-2020-03-25_16-28-41](https://user-images.githubusercontent.com/14242544/77587360-bc915b00-6eb5-11ea-823d-479675a4428f.png)

**Comment by cdown** [comment] 2020-03-25 23:56
Ok, so you need to escape it then to make it a valid BRE. It should be `\\(`.

**Comment by cdown** [comment] 2020-04-01 09:40
Closing for now without prejudice, since I think that we came to an agreement that it's intended behaviour. However, I agree with you that a "literal" mode that doesn't take a regex would also be a nice addition. :-)

**Closed by cdown** 2020-04-01 09:40 UTC
Labels: needs more info
