### ISSUE TITLE
returning from suspend linux

### ISSUE THREAD

**Issue by winchendonsprings** [cdown/clipmenu#26] opened 2015-10-30 20:24 UTC
After returning from suspend climenud appears to be running but calling clipmenu is not populated with newly highlighted/copied items

**Comment by cdown** [comment] 2015-10-31 00:00
How are you suspending? How are you launching X? What error messages are generated from clipmenud after relaunching (try executing it as `clipmenud > /tmp/clog 2>&1`?

My guess is that you're not properly connecting to dbus.

**Comment by winchendonsprings** [comment] 2015-10-31 01:19
I launch X with startx, I suspend with sudo pm-suspend.

I thought clipmenud was running since 

```
~ ps aux | grep clipmenu
ry        1790  0.0  0.0  19888  1168 tty1     S    Oct29   0:21 /bin/bash /home/ry/.clipmenu/clipmenud
ry       10699  0.0  0.0  19888  1312 tty1     S    12:48   0:00 /bin/bash /home/ry/.clipmenu/clipmenud
```
but I was wrong since when I ran the command you mentioned and clipmenu works as expected after relaunching clipmenud

So I guess the problem is the daemon doesn't survive through suspend.

**Comment by kaihendry** [comment] 2015-10-31 01:54
I have this problem too and IIRC the logs were saying Cannot connect to DISPLAY:0

My workaround is [/etc/systemd/system/clipmenud.service](http://ix.io/lca) restarting it. Though it doesn't work perfectly, so don't take this as a fix.

**Comment by cdown** [comment] 2015-10-31 08:19
The way that clipmenud works means that this is consistently a problem. It polls every half a second with xclip or xsel -- the fact that no new selections show up mean it really isn't connecting at all (ie. it's not a transient problem).

When this problem is happening (ie. after suspend and clipmenud stops working), what's the output of `ps -p $(cat /tmp/.X0-lock)` and `date; stat /tmp/.X0-lock /tmp/.X11-unix/X0`?

**Comment by cdown** [comment] 2015-10-31 08:22
Oh, and can you show me `xauth list :0` before and after this issue occurs?

**Comment by fishbullet** [comment] 2015-12-26 23:00
Have the same issue, but not after suspend, just randomly happens.

**Comment by cdown** [comment] 2015-12-26 23:05
Hm. Looks like `clipmenud` got launched twice, and `xsel` is hung?

I need to add more debug logging for this case.

**Comment by cdown** [comment] 2015-12-26 23:06
Also, are all of you launching it through a systemd service? It seems that at least two of you are, maybe it's related.

**Comment by fishbullet** [comment] 2015-12-26 23:09
@cdown it's too hard to understand when this happens. 
It's happens also if i run it in the `.xinitrc`.

**Comment by fishbullet** [comment] 2015-12-26 23:27
That's fun, my `top` show me that the clipmenud related to clipmenud:
```
  406 think     20   0   35,2m   4,4m   0,0  0,1   0:00.40 S  `- systemd
  408 think     20   0   94,7m   1,7m   0,0  0,0   0:00.00 S      `- (sd-pam)
  413 think     20   0   11,9m   2,7m   0,0  0,0   0:03.60 S      `- clipmenud
21208 think     20   0   11,9m   1,8m   0,0  0,0   0:00.00 S          `- clipmenud
21209 think     20   0   15,6m   2,0m   0,0  0,0   0:00.00 S              `- xsel
```

**Comment by cdown** [comment] 2015-12-27 00:23
Thanks for that. I don't really understand how that could happen, but that's very interesting. It at least doesn't seem to be normal behaviour on my machine.

Maybe it's somehow related to the systemd service. Since I also run on a systemd system, I'll try and mimic the problem that way soon.

**Comment by winchendonsprings** [comment] 2016-01-19 01:12
Any updates here? The issue still plagues me but it isn't consistently failing every suspend. I launch it from .xinitrc. At the moment I can't get it to fail after numerous suspends, So it may be happening randomly.

```
~ ps -p $(cat /tmp/.X0-lock)
  PID TTY          TIME CMD
 1599 tty7     00:05:40 Xorg
```

```
~ date; stat /tmp/.X0-lock /tmp/.X11-unix/X0
Mon Jan 18 17:06:58 PST 2016
  File: ‘/tmp/.X0-lock’
  Size: 11        	Blocks: 8          IO Block: 4096   regular file
Device: 801h/2049d	Inode: 136697      Links: 1
Access: (0444/-r--r--r--)  Uid: (    0/    root)   Gid: (    0/    root)
Access: 2016-01-18 17:06:26.186072419 -0800
Modify: 2016-01-15 14:40:16.781447619 -0800
Change: 2016-01-15 14:40:16.781447619 -0800
 Birth: -
  File: ‘/tmp/.X11-unix/X0’
  Size: 0         	Blocks: 0          IO Block: 4096   socket
Device: 801h/2049d	Inode: 262757      Links: 1
Access: (0777/srwxrwxrwx)  Uid: (    0/    root)   Gid: (    0/    root)
Access: 2016-01-15 14:40:16.785447618 -0800
Modify: 2016-01-15 14:40:16.785447618 -0800
Change: 2016-01-15 14:40:16.785447618 -0800
 Birth: -
```

```
This is the same with climenu working or not
~ xauth list :0
g62x/unix:0  MIT-MAGIC-COOKIE-1  a4624051d29ea894a08fa1f935ab9152
```

**Comment by cdown** [comment] 2016-01-19 10:17
I've not been able to reproduce this suspending to disk or suspending to hibernate on Arch Linux.

If you suddenly can't connect to the display after reboot, I'd be willing to bet that dbus is unhappy for some reason.

Out of curiosity, what do `hostname` and `hostname -f` return? I remember there was some issue before when the hostname was set to "localhost".

It would also be nice to see a sample Xorg.0.log, perhaps the old server got terminated and was restarted by systemd.

**Comment by cdown** [comment] 2016-01-19 10:17
Whoops.

**Comment by winchendonsprings** [comment] 2016-01-20 20:20
```
~ hostname   
g62x
~ hostname -f
g62x
~
```
also 
`~ cat /var/log/Xorg.0.log | grep clipmenu` has returned nothing

**Comment by kaihendry** [comment] 2016-02-29 05:39
Different error message, same problem. i.e. clipmenu failing to work from suspend.

<img src=http://s.natalian.org/2016-02-29/1456724234_1912x1036.png>

http://s.natalian.org/2016-02-29/clipmenud.service

**Comment by cdown** [comment] 2016-02-29 12:08
I think that error message is unrelated -- the `STRING` target is unavailable when you copy something not string-like -- for example, an image.

**Comment by Link-Satonaka** [comment] 2016-03-05 18:21
I also have this issue, I run clipmenu from xinitrc. I periodically have to pkill clipmenud and running it again.

**Comment by cdown** [comment] 2016-11-02 22:51
e8ebe8b adds a bunch of debug logging, can you see how this looks if you run with `DEBUG=1` in the environment?

This will print a lot, so you probably want to put output in a file.

**Comment by cdown** [comment] 2016-11-04 16:31
I think @kaihendry reports at least his problem is fixed.

**Comment by cdown** [comment] 2016-11-05 18:10
Closing out as I believe this is fixed by Closing out as I believe this is fixed. It may also be related to https://github.com/cdown/clipmenu/issues/33#issuecomment-258630443

Either way let's discuss in #33 :-)

**Closed by cdown** 2016-11-05 18:10 UTC
Labels: needs more info
