### ISSUE TITLE
[Feature Request] Directly pasting the selected clip in addition to storing into clipboard buffer

### ISSUE THREAD

**Issue by mi-lad** [cdown/clipmenu#136] opened 2020-08-16 10:31 UTC
I almost always want to "paste" something from my clipboard history which means in clipmenu's current form I first have to select the clip and then paste manually. It'd be nice if there was an option to do this in one go. One way I can think of implementing this would be doing something like below at the very end:

```
echo "$chosen_clip" | tr -d '\n' | xclip -selection clipboard
xdotool key Shift+Insert
```

**Comment by cdown** [comment] 2020-08-16 10:34
Hi! This looks like a duplicate of https://github.com/cdown/clipmenu/issues/129. I'd suggest you reply to the existing concerns there :-)

**Closed by cdown** 2020-08-16 10:34 UTC
