### ISSUE TITLE
Sometimes it does not copy

### ISSUE THREAD

**Issue by king-c** [cdown/clipmenu#104] opened 2019-03-18 09:03 UTC
Hello,

So I have clipmenu installed alongside clipnotify however when I select and copy sometimes it just does not work (You go to paste and there is nothing in the clipboard). If you go back to copy again it may or may not work. So I have got into the habit now if pressing Ctrl+C about 5 times before I move away, to ensure its actually in the clipboard. Is there something I have not configured correctly? I cant see any other issues on github that mentions this so I am assuming no-one else has this issue?

Thanks

Chris

**Comment by kaihendry** [comment] 2019-03-18 09:25
I think I have this problem, but I've yet to figure it out.

**Comment by cdown** [comment] 2019-04-28 07:15
Are there any commonalities in what you're trying to copy from? It's possible there's fighting between different clipboard managers for authority.

I personally don't have this issue, so I'm inclined to believe it's some environment-specific issue. However, without knowing exactly what causes it, it's going to be hard to debug.

**Comment by evgenux** [comment] 2019-10-15 16:07
I have the same problem. Its solution is to prevent clipmenu operate with `primary`.  
Setting ` "${CM_SELECTIONS=clipboard}"` in clipmenud does not help.

**Comment by cdown** [comment] 2019-10-15 16:35
Huh, why do you think that's the solution if you're not having success with `CM_SELECTIONS`?

**Comment by evgenux** [comment] 2019-10-16 15:44
Because it is obvious, that `primary` interferes with the list of clips.  
How can I prevent `clipmenu` to look into `primary`?

**Comment by evgenux** [comment] 2019-10-29 12:11
Hi @cdown,  
I identified source of my problem. I was misleaded by [clipboard patch](https://st.suckless.org/patches/clipboard/) applied to my `st` termemu.  
Sorry for a dummy trail.

**Comment by cdown** [comment] 2019-10-29 12:31
Hmm, if it also sets CLIPBOARD that should still work. What exactly happens?

Cc: @kaihendry who is listed on that patch

**Comment by evgenux** [comment] 2019-10-29 18:47
> What exactly happens?

I turned off `primary` in clipmenu. When I was clicking on `st` window to switch focus on it, `st` was sending `\n` symbol to `clipboard`. So I thought, that `clipmenu` sometimes didn't copy.  
Now, without *clipboard patch* `st` sends to clip only by pressing `ctrl+shift+v`.

**Comment by cdown** [comment] 2020-03-24 01:29
I believe I know the cause for this issue, and it should be fixed in 6.0.0, specifically f22fce7f0407b6ace997599827b9f9ab01ad5c3f. Please let me know if 6.0.0 still has issues for you :-)

**Closed by cdown** 2020-03-24 01:29 UTC
Labels: needs more info
