### ISSUE TITLE
Clipmenu doesn't function correctly when started using systemd service

### ISSUE THREAD

**Issue by marc1984** [cdown/clipmenu#141] opened 2020-10-15 15:58 UTC
OS: Arch 
Clipmenu 6.1.0

Clipmenu doesn't seem to work correctly when started using `systemctl --user enable clipmenud`. After restarting, clipmenud seems to be running (+clipnotify as well), however clipmenu is not able to copy any text. 

![systemctl_clipmenud_status](https://user-images.githubusercontent.com/9002794/96155001-b75a3300-0f0f-11eb-84aa-973831ccdf5e.png)

**Comment by cdown** [comment] 2020-10-15 20:47
Can you please try to reproduce with 6.2.0? There are a number of changes in there.

Other than that, can you please run with `CM_DEBUG=1`, and report the output of `journalctl -u clipmenud` for that session? :-)

Also, does `clipnotify` change PID?

**Comment by cdown** [comment] 2020-10-16 21:33
What's your current $DISPLAY? Is it the same as in /proc/23293/environ?

**Comment by KarlWithK** [comment] 2020-10-16 22:40
Hey, I also have a similar issue: 
OS: arch
Verison of package: 6.2.0.1
![image](https://user-images.githubusercontent.com/31679231/96319803-af1cf900-0fde-11eb-9a09-7a37b131a390.png)

and when I try to run `$ clipmenu` I get this error:
![image](https://user-images.githubusercontent.com/31679231/96319886-e25f8800-0fde-11eb-9a80-52b77b33152b.png)


I downgraded to 6.1.0.2 and everything works. No journal logs since the service doesn't start.

**Comment by cdown** [comment] 2020-10-16 23:43
Are you sure your $DISPLAY is set correctly with `systemctl --user import-environment DISPLAY` or similar?

**Comment by KarlWithK** [comment] 2020-10-17 11:50
So I checked to see if that was the problem and this is what I got:
![image](https://user-images.githubusercontent.com/31679231/96336375-50429880-104d-11eb-9ce0-cd940cb45453.png)
My display is set.

**Comment by cdown** [comment] 2020-10-17 12:37
That's way too late to import, you need to do it prior to starting systemd. Exit code 2 literally means "`$DISPLAY` is unset" :-)

**Comment by drot** [comment] 2020-10-17 14:23
If this issue is about `startx`, at least on Arch the `/etc/X11/xinit/xinitrc` file by default loads the `/etc/X11/xinit/xinitrc.d/50-systemd-user.sh` drop-in which already does the job of importing the environment:

```
#!/bin/sh

systemctl --user import-environment DISPLAY XAUTHORITY

if command -v dbus-update-activation-environment >/dev/null 2>&1; then
    dbus-update-activation-environment DISPLAY XAUTHORITY
```
The issue here is simply using `startx` and enabling the `clipmenud` service won't quite work since naturally the service gets started before it has a chance to "see" any `DISPLAY`, thus to solve the problem (rather naively) I simply start the unit manually in my `.xinitrc` without enabling it.

**Comment by cdown** [comment] 2020-10-17 19:06
Closing this since, judging by the thumbs up, that explains what's going on. The X server must be started before clipmenud so that systemd knows the $DISPLAY to be pushed into the environment.

**Closed by cdown** 2020-10-17 19:06 UTC
Labels: needs more info
